name: LeeesNN
main: Leees.nick.Main
description: Leees Nick Namer
author: Nate Legault
version: 3.0

commands:
  LeeesNN:
    aliases: [nick]
    description: Nickname yourself
  resetnick:
    description: clear your nick
    